/*
 * Generated by Bluespec Compiler (build 9f4a447)
 * 
 * On Tue Jun 16 12:18:14 IST 2020
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkbarrelNtb_h__
#define __mkbarrelNtb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkbarrelNtb module */
class MOD_mkbarrelNtb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_state;
 
 /* Constructor */
 public:
  MOD_mkbarrelNtb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_go;
  tUInt8 DEF_CAN_FIRE_RL_go;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_go();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkbarrelNtb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkbarrelNtb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkbarrelNtb &backing);
};

#endif /* ifndef __mkbarrelNtb_h__ */
