/*
 * Generated by Bluespec Compiler (build 9f4a447)
 * 
 * On Tue Jun 16 12:18:14 IST 2020
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkbarrelNtb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkbarrelNtb::MODEL_mkbarrelNtb()
{
  mkbarrelNtb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkbarrelNtb()
{
  MODEL_mkbarrelNtb *model = new MODEL_mkbarrelNtb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkbarrelNtb &INST_top = *((MOD_mkbarrelNtb *)(instance_ptr));
	 tUInt32 DEF_INST_top_DEF__read__h49;
	 DEF_INST_top_DEF__read__h49 = INST_top.INST_state.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_go = DEF_INST_top_DEF__read__h49 == 0u;
	 INST_top.DEF_WILL_FIRE_RL_go = INST_top.DEF_CAN_FIRE_RL_go;
	 if (INST_top.DEF_WILL_FIRE_RL_go)
	   INST_top.RL_go();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_state.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkbarrelNtb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkbarrelNtb_instance = new MOD_mkbarrelNtb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkbarrelNtb_instance->set_clk_0)("CLK");
}
void MODEL_mkbarrelNtb::destroy_model()
{
  delete mkbarrelNtb_instance;
  mkbarrelNtb_instance = NULL;
}
void MODEL_mkbarrelNtb::reset_model(bool asserted)
{
  (mkbarrelNtb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkbarrelNtb::get_instance()
{
  return mkbarrelNtb_instance;
}

/* Fill in version numbers */
void MODEL_mkbarrelNtb::get_version(unsigned int *year,
				    unsigned int *month,
				    char const **annotation,
				    char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "9f4a447";
}

/* Get the model creation time */
time_t MODEL_mkbarrelNtb::get_creation_time()
{
  
  /* Tue Jun 16 06:48:14 UTC 2020 */
  return 1592290094llu;
}

/* State dumping function */
void MODEL_mkbarrelNtb::dump_state()
{
  (mkbarrelNtb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkbarrelNtb & mkbarrelNtb_backing(tSimStateHdl simHdl)
{
  static MOD_mkbarrelNtb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkbarrelNtb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkbarrelNtb::dump_VCD_defs()
{
  (mkbarrelNtb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkbarrelNtb::dump_VCD(tVCDDumpType dt)
{
  (mkbarrelNtb_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkbarrelNtb_backing(sim_hdl));
}
