/*
 * Generated by Bluespec Compiler (build 9f4a447)
 * 
 * On Tue Jun 16 12:18:14 IST 2020
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkbarrelNtb_h__
#define __model_mkbarrelNtb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkbarrelNtb.h"

/* Class declaration for a model of mkbarrelNtb */
class MODEL_mkbarrelNtb : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkbarrelNtb *mkbarrelNtb_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkbarrelNtb();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkbarrelNtb();
}

#endif /* ifndef __model_mkbarrelNtb_h__ */
